### ISSUE TITLE
15s delay

### ISSUE THREAD

**Issue by ggauzin** [GoodbyeNJN/Flow.Launcher.Plugin.OneTimePassword#1]

**Comment by GoodbyeNJN** [comment]
Please explain your issue in detail.

**Comment by ggauzin** [comment]
there is no such button like sync clock, so i have a delay of about 15s before an actual otp code shows up. until then the code is outdated

**Comment by GoodbyeNJN** [comment]
The plugin uses the system clock to generate one-time passwords. If you encounter time-related issues, you should consider synchronizing the system clock.

**Comment by ggauzin** [comment]
just about every authenticator has this feature lol

**Comment by GoodbyeNJN** [comment]
The prerequisite for providing this feature is that the application itself maintains a clock. As mentioned above, this plugin uses the system clock, so it cannot provide this feature.

**Comment by ggauzin** [comment]
thanks for the answer
